create table "MINE".TENNISMATCHES
(
	ID INTEGER not null primary key,
	PLAYER1 VARCHAR(50),
	PLAYER2 VARCHAR(50),
	TIMEMINUTES INTEGER not null,
	ONGOING BOOLEAN default false,
	SETS_PLAYER1 INTEGER not null,
	SETS_PLAYER2 INTEGER not null,
	GAMES_PLAYER1 INTEGER not null,
	GAMES_PLAYER2 INTEGER not null,
	POINTS_PLAYER1 INTEGER,
	POINTS_PLAYER2 INTEGER
);

INSERT INTO "TENNISMATCHES" VALUES (3424,'john', 'peter',63,'true',1,1,4,4,3,3);

